import { ApiProperty } from '@nestjs/swagger';

export class MetricSummaryDto {
  @ApiProperty({ description: 'Gross sales revenue in IDR' })
  grossSales: number;

  @ApiProperty({ description: 'Percentage change vs previous period' })
  grossSalesChange: number;

  @ApiProperty({ description: 'Total number of orders placed in period' })
  totalOrders: number;

  @ApiProperty({ description: 'Percentage change in order volume' })
  totalOrdersChange: number;

  @ApiProperty({ description: 'Total physical pieces currently in inventory across all variants' })
  totalPiecesInStock: number;

  @ApiProperty({ description: 'Total units sold in period' })
  totalPiecesSold: number;

  @ApiProperty({ description: 'Count of variants at or below low stock threshold' })
  lowStockItemsCount: number;

  @ApiProperty({ description: 'Count of distinct active customers' })
  activeCustomers: number;

  @ApiProperty({ description: 'Percentage change in active customer count' })
  activeCustomersChange: number;

  @ApiProperty({ description: 'Average order value in IDR' })
  averageOrderValue: number;
}

export class SalesTrendPointDto {
  @ApiProperty({ description: 'Date label (e.g. 28 Aug)' })
  date: string;

  @ApiProperty({ description: 'Gross sales for the day in IDR' })
  sales: number;

  @ApiProperty({ description: 'Number of orders placed on this day' })
  orders: number;
}

export class CapsuleShareDto {
  @ApiProperty({ description: 'Collection/Capsule identifier (e.g. FORM)' })
  code: string;

  @ApiProperty({ description: 'Collection name' })
  label: string;

  @ApiProperty({ description: 'Capsule tagline' })
  tagline: string;

  @ApiProperty({ description: 'Share percentage (0-100)' })
  share: number;

  @ApiProperty({ description: 'Number of pieces sold in this capsule' })
  pieces: number;

  @ApiProperty({ description: 'Total revenue generated by this capsule in IDR' })
  revenue: number;

  @ApiProperty({ description: 'Accent background color class' })
  color: string;

  @ApiProperty({ description: 'Accent text color class' })
  textColor: string;
}

export class TopSellingProductDto {
  @ApiProperty({ description: 'Product UUID' })
  id: string;

  @ApiProperty({ description: 'Product Name' })
  name: string;

  @ApiProperty({ description: 'Product Slug' })
  slug: string;

  @ApiProperty({ description: 'SKU Root' })
  skuRoot: string;

  @ApiProperty({ description: 'Category Name' })
  category: string;

  @ApiProperty({ description: 'Units sold' })
  unitsSold: number;

  @ApiProperty({ description: 'Total revenue generated in IDR' })
  revenue: number;

  @ApiProperty({ description: 'Primary image URL', required: false, nullable: true })
  imageUrl?: string | null;
}

export class LowStockAlertDto {
  @ApiProperty({ description: 'Inventory UUID' })
  id: string;

  @ApiProperty({ description: 'Variant UUID' })
  variantId: string;

  @ApiProperty({ description: 'Product UUID' })
  productId: string;

  @ApiProperty({ description: 'Product Name' })
  productName: string;

  @ApiProperty({ description: 'Variant SKU' })
  sku: string;

  @ApiProperty({ description: 'Color name' })
  color: string;

  @ApiProperty({ description: 'Size' })
  size: string;

  @ApiProperty({ description: 'Total quantity on hand' })
  stock: number;

  @ApiProperty({ description: 'Reserved quantity' })
  reserved: number;

  @ApiProperty({ description: 'Available quantity (stock - reserved)' })
  available: number;

  @ApiProperty({ description: 'Low stock threshold' })
  threshold: number;

  @ApiProperty({ description: 'Stock status', enum: ['LOW_STOCK', 'OUT_OF_STOCK', 'IN_STOCK'] })
  status: 'LOW_STOCK' | 'OUT_OF_STOCK' | 'IN_STOCK';
}

export class RecentOrderSummaryDto {
  @ApiProperty({ description: 'Order UUID' })
  id: string;

  @ApiProperty({ description: 'Order Number (NOV-YYYY-XXXX)' })
  orderNumber: string;

  @ApiProperty({ description: 'Customer Name' })
  customerName: string;

  @ApiProperty({ description: 'Customer Email' })
  customerEmail: string;

  @ApiProperty({ description: 'Shipping City' })
  shippingCity: string;

  @ApiProperty({ description: 'Total number of items in order' })
  itemCount: number;

  @ApiProperty({ description: 'Total order amount in IDR' })
  totalAmount: number;

  @ApiProperty({ description: 'Order Status' })
  status: string;

  @ApiProperty({ description: 'Creation ISO date' })
  createdAt: string;
}

export class CustomerActivityDto {
  @ApiProperty({ description: 'Total registered customer accounts' })
  totalCustomers: number;

  @ApiProperty({ description: 'New customers registered in window' })
  newCustomers: number;

  @ApiProperty({ description: 'Active carts currently open' })
  activeCarts: number;

  @ApiProperty({ description: 'Total wishlist items saved across all users' })
  totalWishlistItems: number;
}

export class StyleFinderMetricDto {
  @ApiProperty({ description: 'Total completed style profiles' })
  totalProfiles: number;

  @ApiProperty({ description: 'Distribution by style archetype code' })
  archetypeDistribution: Record<string, number>;
}

export class DashboardOverviewResponseDto {
  @ApiProperty({ type: MetricSummaryDto })
  metrics: MetricSummaryDto;

  @ApiProperty({ type: [SalesTrendPointDto] })
  salesTrend: SalesTrendPointDto[];

  @ApiProperty({ type: [CapsuleShareDto] })
  capsuleDistribution: CapsuleShareDto[];

  @ApiProperty({ description: 'Order counts grouped by OrderStatus' })
  orderStatusDistribution: Record<string, number>;

  @ApiProperty({ type: [TopSellingProductDto] })
  topSellingProducts: TopSellingProductDto[];

  @ApiProperty({ type: [LowStockAlertDto] })
  lowStockAlerts: LowStockAlertDto[];

  @ApiProperty({ type: [RecentOrderSummaryDto] })
  recentOrders: RecentOrderSummaryDto[];

  @ApiProperty({ type: CustomerActivityDto })
  customerActivity: CustomerActivityDto;

  @ApiProperty({ type: StyleFinderMetricDto })
  styleFinder: StyleFinderMetricDto;
}
